/******************************************
Treehouse Techdegree:
FSJS project 1 - A Random Quote Generator
******************************************/

// Element Selector
const quoteBox = document.querySelector('#quote-box');
const body = document.querySelector('body');

// Array of objects storing quotes and their corresponding data
const quotes = [
              {quote: 'Do not fear to be eccentric in opinion, for every opinion now accepted was once eccentric.',
              source: 'Bertand Russell',
              year: 1930,
              citation: 'The Conquest of Happiness',
              likes: 7},
              {quote: 'Time makes more converts than reason',
              source: 'Thomas Paine',
              year: 1930,
              citation: 'Common Sense'},
              {quote: 'If you\'re walking down the right path and you\'re willing to keep walking, eventually you\'ll make progress.',
              source: 'Barack Obama',
              likes: 4},
              {quote: 'In order to understand the world, one has to turn away from it on occasion.',
              source: 'Albert Camus',
              year: 1942,
              citation: 'The Minotaur'},
              {quote: 'Study Bach, there you will find everything.',
              source: 'Johannes Brahms',
              citation: 'Wikipedia',
              likes: 3}
            ]

/***
getRandomQuote function returns a random value from the array that is passed.
***/
function getRandomQuote(array) {
    let randNum = Math.floor((Math.random() * array.length));
    return array[randNum];
}


/***
  - The printQuote function stores the returned quote object from the genRandomQuote function in a variable.
  - HTML is then concatenated with content being dynamically generated by accessing the properties of the stored quote object.
  Conditional statements check if 'citation' and 'year' properties exist and are added if they do.
  - The concatenated html is inserted into the div with the class quote-box.
***/

function printQuote() {
  let htmlString = '';
  let randomQuote = getRandomQuote(quotes);
  htmlString += `<p class="quote">${randomQuote['quote']}</p>`;
  htmlString += `<p class="source">${randomQuote['source']}`;
  if (randomQuote.hasOwnProperty('citation')) {
    htmlString += `<span class="citation">${randomQuote['citation']}</span>`;
  }
  if (randomQuote.hasOwnProperty('year')) {
    htmlString += `<span class="year">${randomQuote['year']}</span></p>`;
  }
  if (randomQuote.hasOwnProperty('likes')) {
    htmlString += `</p><div class="likes"><p>${randomQuote['likes']} </p><i class="far fa-thumbs-up"></i></div>`;
  }
  else htmlString += `</p>`;
  quoteBox.innerHTML = htmlString
}

// Function generates a random rbg value then adds it to the body of the page
function changeBackgroundColor() {
  let round = Math.round;
  let random = Math.random;
  const rgbaLimit = 255;
  let random_rgba = `rgba(${round(random()*rgbaLimit)},${round(random()*rgbaLimit)},${round(random()*rgbaLimit)},${random().toFixed(1)})`;
  body.style.backgroundColor = random_rgba;
};

/***
  Handler triggers printQuote function when #loadQuote element is clicked.
***/

document.getElementById('loadQuote').addEventListener("click", () => {
  printQuote();
  changeBackgroundColor();
}, false);

// Calls the printQuote and changeBackgroundColor functions at the specified interval in the callback.
setInterval(function(){
    printQuote();
    changeBackgroundColor();
  }, 20000);
